### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/soliloquy#3]
Since this is a gem and wasn't audited, I am just opening up a Github issue. It will be a little more difficult to tag lines of the code, but we'll do our best.

My question is, why is this class necessary?

https://github.com/department-of-veterans-affairs/soliloquy/blob/master/lib/soliloquy/overrides/action_controller/instrumentation.rb#L2

My understanding is that the process_action method is sort of the equivalent of a "method_missing" for controllers, is it a good idea to be overriding that method?

**Comment by kreek** [comment]
This was for logging additional request parameters, but in the latest PR adds rails tagging support so we no longer need to modify the 'process_action.action_controller' event in ActionController::Instrumentation#process_action.
